### ISSUE TITLE
IE compatibility?

### ISSUE THREAD

**Issue by noseboy** [qodesmith/datepicker#19]
I have some IE9/10 users and the datepicker doesn't seem to work - works fine on Chrome.  Is this a known issue?

**Comment by porpoisepower** [comment]
I'm trying to adapt this to work with IE (since I have this problem with IE 11.) 

So this is a post in process, as I work through issues.  Hopefully this will be helpful to the authors of this package.

Lines 42 and 163 uses 'deconstructed object assignment' which IE doesn't support ( I had the same issue with IE 11)  I replaced the line with individual assignments ( 
for example I replace 42  with

    const startDate = options.startDate
    const selectedDate = options.selectedDate)

Line 136 uses e => {...} instead of function(e){...}  => is shorthand, (there's some other differences with this, but I didn't see it used in the function, so I think it'll be okay to the regular version)

**Comment by qodesmith** [comment]
Hey @porpoisepower, sorry for the delayed response. You should be using the `datepicker.min.js` file as it has already been transpiled down to ES5 and will be compatible with IE. Let me know if that works.

**Comment by noseboy** [comment]
Hi, I'm using it on IE8 and IE11 - datepicker.min.js doesn't seem to work
for these.  Works fine with Chrome etc.

**Comment by qodesmith** [comment]
@noseboy Datepicker is using a [mutation observer](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) and it looks like that's [incompatible](http://caniuse.com/#search=mutationObser) with IE < 11. But can you tell me what error you're getting with IE 11 specifically?

**Comment by noseboy** [comment]
At the line if (q.includes(t) throw new Error.... the console tells me that
'Object doesn't support property or method 'includes' at line 1 column 1615

**Comment by qodesmith** [comment]
@noseboy Ahhh, I see. `Array.includes` isn't supported in IE, only in Edge. Let me make some changes to the code.

**Comment by qodesmith** [comment]
@noseboy @porpoisepower Ok my friends. I've revamped the code towards being more IE friendly. There's no more mutation observer and it now includes a very small polyfill for `Array.includes`. I'd love to know how things work for you guys and if there's still IE errors. As always, please use the `datepicker.min.js` file.

**Comment by qodesmith** [comment]
Closing this issue. If there's still IE troubles, don't hesitate to open another ticket.
