### ISSUE TITLE
'Fixed' Positioning option for small devices

### ISSUE THREAD

**Issue by Lambo232** [qodesmith/datepicker#31]
This is a great datepicker, ideal for what I needed.  However I had a problem positioning the calendar on a small device such as a mobile phone in portrait mode where all of the current options often end up with part of the calendar off screen.

I have modified the code to include a 'fixed' positioning option that positions the calendar in the middle of the view port.  I have attached the
[datepicker.zip](https://github.com/qodesmith/datepicker/files/2018893/datepicker.zip)
 modified version in case you are interested in including the option in the base (you may be able to improve on my method as well).

Cheers.

**Comment by qodesmith** [comment]
@Lambo232 Thanks for the idea. I took a look at your code and implemented things in a similar way. There's now a new position option which achieves what you wanted:

```javascript
datepicker('.some-class', { position: 'c' });
```
Instead of setting the `style` attribute, I'm using a class in the css to do the heavy lifting. Also, just as an aside, I tried playing around on mobile and didn't have any issues with the Calendar not showing or being cut off. One thing that _was_ an issue was the native keyboard pops up and gets in the way. This can be avoided by putting `readonly="true"` on the input element you're using.

Example:
```html
<input id="dp" type="text" readonly="true" />
```
```javascript
datepicker('#dp', { position: 'c' });
```

Thanks for taking the time out to flesh out this idea!
