### ISSUE TITLE
disabledDates dosent's work

### ISSUE THREAD

**Issue by pengjinlong** [qodesmith/datepicker#32]
here is my codes

var options = {
            minDate: new Date(),
            position: 'c',
            customMonths: ['一月','二月','三月','四月','五月','六月','七月','八月','九月','十月','十一月','十二月'],
            customDays: ['周天','周一','周二','周三','周四','周五','周六'],
            disabledDates: [new Date('27/6/2018'), new Date('28/5/2018')],
            onSelect: function(instance) {
                // Show which date was selected.
                console.log(instance.dateSelected.toLocaleString());
            }
        }
var picker = datepicker('.date',options);

**Comment by qodesmith** [comment]
@pengjinlong I just ran your code. The issue is the dates you are providing are invalid. Typing these into Chrome's console reveals the issue:
<img width="215" alt="screen shot 2018-05-23 at 8 38 03 am" src="https://user-images.githubusercontent.com/11034792/40424840-a6c8a26e-5e64-11e8-80c4-3ee66b0490f4.png">

Did you mean something like `new Date('6/27/2018')` instead? Try that and see if that's what you intended. In the meantime, I could implement some sort of warning about providing invalid dates.

**Comment by qodesmith** [comment]
Ok, new version published. Now, you will see this error in the console when providing an invalid date:
<img width="584" alt="screen shot 2018-05-23 at 8 56 52 am" src="https://user-images.githubusercontent.com/11034792/40425782-5682a9be-5e67-11e8-9f5b-4632cc90a084.png">

Let me know if you have any more issues!
