### ISSUE TITLE
Connected calendars UX issues

### ISSUE THREAD

**Issue by andrejcremoznik** [qodesmith/datepicker#64]
Selecting dates on each calendar currently adjusts min and max date. This locks the range and unless you know to re-click the selected day, you can't get out of it.

* `minDate` should be used to set the earliest accessible date
* `maxDate` should be used to set the latest accessible date
* `maxDate` and `minDate` should be independent per instance
* selecting a date on the 1st calendar should set minDate on the 2nd calendar
* selecting a date on the 2nd calendar should **not** set/change maxDate on the 1st
* having an extra class on the days in the daterange would be nice

What do you think?

**Comment by qodesmith** [comment]
Hey @andrejcremoznik. Some thoughts...

> Selecting dates on each calendar currently adjusts min and max date. This locks the range and unless you know to re-click the selected day, you can't get out of it.

This is exactly how it's supposed to work. When dealing with a date _range_ picker, one would expect the selected range to be enabled and dates outside the range to be disabled. The bit about having to re-click detailed in the readme instructions so users should be aware.

---

> `minDate` should be used to set the earliest accessible date
> `maxDate` should be used to set the latest accessible date

This _is_ how the calendar currently works.

---

> `maxDate` and `minDate` should be independent per instance

This isn't feasible for connected calendars. A daterange picker has a single `minDate` and `maxDate` for the _pair_. Otherwise you'd just have two separate calendars, which you can still totally do.

---

> selecting a date on the 1st calendar should set `minDate` on the 2nd calendar

Again, this is already how the calendar works.

---

> selecting a date on the 2nd calendar should **not** set/change maxDate on the 1st

Curious, why this feature? It seems intuitive that if you select a date on the 2nd calendar - essentially the "end" calendar - then the 1st should reflect that in its range. I'm not sure I understand your intentions here.

---

> having an extra class on the days in the daterange would be nice

What did you have in mind to use the classes for? Styling? Just curious. This would be a simple addition to the library.

I appreciate you taking the time to give feedback. Help me understand your ideas. Thanks man.

**Comment by andrejcremoznik** [comment]
Hey, so there's a fundamental difference between our ideas how range pickers should be. I'll try to explain on an example. Take a look at https://www.booking.com/

![Screenshot_20190926_110446](https://user-images.githubusercontent.com/761287/65674868-8af61f00-e04d-11e9-9c51-0038d4204a08.png)

**Today's date** (sep.26) is the first available date. It doesn't allow the user to select a date prior to this date, because it makes no sense in the context of booking a hotel. **Your calendar's** `minDate` does not set this value. Your `minDate` is not actually "min date", it's the "range start day". Likewise, your `maxDate` is not the actual "max date" available for selection, it's the "range end day".

Here's the shift in thinking between Booking's and your implementation;
```
min date !== range start date && max date !== range end date
```

You do not have a "range start/range end" and instead use the "min/max" values for that. This essentially breaks convention. Conventions are important for end users and reclicking a date to "unlock for reselection" is so unconventional, it will affect conversions in a baaaaad way.

> The bit about having to re-click detailed in the readme instructions so users should be aware.
Developers will be aware, users won't.

What I'm doing right now to avoid this issue is basically resetting the selected date if the user reopens the calendar and I'd rather not do so. I'd also rather not use a different library since I quite like your simple implementation.

> What did you have in mind to use the classes for? Styling?

Yes, If you understand what I'm getting at here and introduce a `rangeStart/rangeEnd` in addition to `minDate/maxDate` such a class to mark the range will actually be a necessity.

Anyway, what Booking does is the convention. I didn't know of a single date range picker that didn't do it that way until this one. I hope you'll see why adopting conventional UX would be beneficial. I don't have the time now, but when I do I'll look at the code and see if I can help make things better.

**Comment by qodesmith** [comment]
I think I see what you're saying. In essence, the _selectable_ range should be set by the min / max dates, but a user should be free to click within those dates without having to re-click to unselect - it should just work since it's within the _selectable_ range, correct? If so, then I see why the extra class name is necessary because you would need a visual cue for the _select**ed**_ range within the _select**able**_ range. Let me know if I'm close here. And if this is the way folks are used to a range picker behaving, then I'll definitely want to change things.

**Comment by andrejcremoznik** [comment]
Yes, you're correct.

However, I think introducing a separate option to also configure range limits (e.g. no date before X, no date after Y) would be required, hence I'm suggesting the `rangeStart/rangeEnd` for the selected values and `minDate/maxDate` for actual limits. Semantically this would be more correct, but code wise you're probably currently using `minDate/maxDate` as selected values.

I guess in this case you could add `minDateLimit/maxDateLimit` or similar to configure that.

**Comment by qodesmith** [comment]
I took a look at some daterange pickers we use here at Facebook, and they operate more like how you described. This will take me a bit to change so I might not have time to get to this right away. But I agree that this library should work the way folks are used to. You're the first person to mention it! Albeit the daterange functionality hasn't been out that long, but still. I appreciate the insight and I'll get to this when I can carve out some time.

**Comment by DerekDenHartigh** [comment]
I ended up using this date-picker for a project and to make it so that your first datepicker will respect your initial minDate and your second datepicker will respect your initial maxDate and not reset those mins/maxs to the selected dates you can modify the adjustDateRanges function like this:
```
function adjustDateranges({ instance, deselect }) { //recall
    const first = instance.first ? instance : instance.sibling
    const second = first.sibling

    if (first === instance) {
        if (deselect) {
            first.minDate = first.originalMinDate
            second.minDate = second.originalMinDate
        } else {
            //first.minDate = first.dateSelected
            first.minDate = first.originalMinDate
            second.minDate = first.dateSelected
        }
    } else {
        if (deselect) {
            second.maxDate = second.originalMaxDate
            first.maxDate = first.originalMaxDate
        } else {
            //second.maxDate = second.dateSelected
            second.maxDate = second.originalMaxDate
            first.maxDate = second.dateSelected
        }
    }
}
```
or if you're referencing the minified version for compatability:
```
function y(e) { var t = e.instance, n = e.deselect, a = t.first ? t : t.sibling, r = a.sibling; a === t ? n ? (a.minDate = a.originalMinDate, r.minDate = r.originalMinDate) : (a.minDate = a.dateSelected, r.minDate = a.dateSelected) : n ? (r.maxDate = r.originalMaxDate, a.maxDate = a.originalMaxDate) : (r.maxDate = r.dateSelected, a.maxDate = r.dateSelected) }
```
replace with:
```
function y(e) { var t = e.instance, n = e.deselect, a = t.first ? t : t.sibling, r = a.sibling; a === t ? n ? (a.minDate = a.originalMinDate, r.minDate = r.originalMinDate) : (a.minDate = a.originalMinDate, r.minDate = a.dateSelected) : n ? (r.maxDate = r.originalMaxDate, a.maxDate = a.originalMaxDate) : (r.originalMaxDate = r.dateSelected, a.maxDate = r.dateSelected) }
```

**Comment by DerekDenHartigh** [comment]
I need to make an adjustment to my solution - it resulted in a bug that when you deselected the second datepicker date it would set the maxDate to the deselected date.  to fix, replace:
```r.maxDate = r.originalMaxDate```
with
```a.maxDate = a.originalMaxDate```
this will cause the second datepicker to respect the min/max as set by the first datepicker of the pair - as the second datepickers mins/maxes are ignored per the documentation.
