### ISSUE TITLE
Triggering toggleOverlay

### ISSUE THREAD

**Issue by mrlg255** [qodesmith/datepicker#81]
Is it possible to trigger toggleOverlay on specified event (onShow etc)? Maybe adding option like "initialView": "dayPicker|monthPicker" would make it easier?

**Comment by qodesmith** [comment]
Can you explain a bit further? Not sure I understand. It sounds like you want the ability to trigger `toggleOverlay` in some manual fashion?

**Comment by mrlg255** [comment]
Yes, I'd like to be able ot trigger `toggleOverlay` programmatically. 
Another thing is that option to open overlay automatically after showing up datepicker would be nice addition - something like `startView` option in bootstrap-datepicker: [ref](https://uxsolutions.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=2&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox)

**Comment by qodesmith** [comment]
Looking into this now...

**Comment by tom2tom** [comment]
How's this coming along?
I too want to use this as a month-picker in some contexts

**Comment by qodesmith** [comment]
Sorry, just started looking into this again. I've got a `toggleOverlay` method working on the picker instance now. Going to get started on the option to show the overlay when the calendar is opened.

**Comment by qodesmith** [comment]
Ok, this is now in the latest version - 5.18.0.

3 things added:
- toggleOverlay - new method to programmatically toggle the overlay.
- defaultView - a new option that enables you to set the overlay as the default view. Simply pass `defaultView: 'overlay'` as an option.
- A minor tweak, but on mobile devices, the overlay year input will now trigger the numeric keypad instead of the default one.
