### ISSUE TITLE
Saturday divs break to next line

### ISSUE THREAD

**Issue by ikirkpat** [qodesmith/datepicker#82]
My saturday column wraps to the next line on MS Edge.

![broken_saturday_column](https://user-images.githubusercontent.com/49094893/77783149-c094b880-702e-11ea-993b-be0287c19c03.PNG)

I inspected and modified the cell width from `width: calc(14.2857%)` to `width: calc(14%)` and it worked fine so I'm sure it's something with the new line after each cell adding width but I'd obviously like to not have to modify the css of the cells to make it work.

**Comment by qodesmith** [comment]
What browser are you using?

**Comment by qodesmith** [comment]
Also, can you try using `calc(100% / 7)` and tell me if that works? In the [SCSS](https://github.com/qodesmith/datepicker/blob/856818266d7ae11c36919b3391f634d64d6d6f8d/src/datepicker.scss#L221) that's what the calculation is, but apparently it's being rendered to a literal percent in the production css. Pretty sure browsers differ in how they calculate sub-pixel rendering. My hope is that if it stays a raw calc computation, the browser is left free to calculate accordingly instead of being forced to a specific percent.

**Comment by qodesmith** [comment]
@ikirkpat I'll need you to confirm before I merge this. Also, I downloaded Edge and couldn't reproduce this. Albeit, I'm on a Mac.

**Comment by qodesmith** [comment]
Ended up merging anyways.
